### ISSUE TITLE
cannot train

### ISSUE THREAD

**Issue by essxnce** [trucleduc/PointGrid#3]
Hello, I'm so surprised your code simplicity.
When I use and your codework, I just have a problem like this : 

-----------------------

jinhyeok@yang:~/PointGrid/code$ python train.py
/home/jinhyeok/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
 Batch Size: 32
 Training using GPU: 1
 Training epoch: 200
Traceback (most recent call last):
  File "train.py", line 206, in <module>
    train()
  File "train.py", line 128, in train
    pred_cat, pred_seg = model.get_model(dequeue_pointgrid, is_training=is_training_ph)
  File "/home/jinhyeok/PointGrid/code/network.py", line 194, in get_model
    cat_features = tf.tile(tf.reshape(tf.concat([fc2, pred_cat], axis=1), [batch_size, 1, 1, 1, -1]), [1, N/16, N/16, N/16, 1])
  File "/home/jinhyeok/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/gen_array_ops.py", line 8805, in tile
    "Tile", input=input, multiples=multiples, name=name)
  File "/home/jinhyeok/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 609, in _apply_op_helper
    param_name=input_name)
  File "/home/jinhyeok/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 60, in _SatisfiesTypeConstraint
    ", ".join(dtypes.as_dtype(x).name for x in allowed_list)))
TypeError: Value passed to parameter 'multiples' has DataType float32 not in list of allowed values: int32, int64

---------

I don't know why this situation just happened...

Jinhyeok

**Comment by zpluoxmu** [comment]
I also have this problem. I modified the  "N/16"  to  "int(N/16)", then it can work. May be you can try this way.

**Comment by xuwang1988** [comment]
It is Python 2 code. Don't run it on Python 3.6.

**Comment by clin-fu** [comment]
@xuwang1988 Hello, have you run this program already?I have a problem with the. Mat data format .Can you give me some help?

**Comment by LebronGG** [comment]
I have a problem with the. Mat data format .I don't know how to convert ShapeNet data to .Mat data. 
Can you give me some help?

**Comment by clin-fu** [comment]
@LebronGG   hellow,we met the same question  i cover the m40 to .mat ,But the program reported  error,so i read the train.py to see how to read the data and chage the format ,I tried many times but all failed .Can we solve the problem together?Exchange ideas
